steps:
  - name: gcr.io/cloud-builders/mvn
    args:
      - install
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'
  - name: gcr.io/cloud-builders/kubectl
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    args:
      - set
      - image
      - 'deployment/${_DEPLOYMENTNAME}'
      - '${_CONTAINERNAME}=gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
